### ISSUE TITLE
markdown window can't marked color in single view

### ISSUE THREAD

**Issue by amazinghaha** [ajilderda/joplin-macos-native-theme#11]
![image](https://user-images.githubusercontent.com/77572673/129475106-2a44fcbf-8044-4e05-8732-503b9a355df1.png)![image](https://user-images.githubusercontent.com/77572673/129475137-7af26848-5ac4-4d03-af1f-4669f3aaa312.png)

**Comment by ajilderda** [comment]
I've just pushed an update that should fix this issue. Let me know if that's not the case. Thanks for reporting!
