### ISSUE TITLE
Insert Link dialog

### ISSUE THREAD

**Issue by andrei-a-papou** [ajilderda/joplin-macos-native-theme#13]
![image](https://user-images.githubusercontent.com/30468319/129641112-3542af79-8acb-4991-a008-c99312067d3c.png)

The dialog (_Ctrl-K_) doesn't look like an Electron one, maybe it's some kinda JS modal dialog, not sure. But it certainly doesn't blend in. 

Is there any way to style it also?

P.S. Seems that the theme's vertical dividers appear on top of the modal's background.

**Comment by ajilderda** [comment]
@andrei-a-papou With the latest release it should look better. ;)

**Comment by andrei-a-papou** [comment]
Looks great now, thanks!
