### ISSUE TITLE
<a> tags don't have pointer

### ISSUE THREAD

**Issue by DanielNetoP** [ajilderda/joplin-macos-native-theme#14]
Hi, on the preview of the markdown the `a` tags are with `cursor: default` instead of `cursor: pointer`, this makes the little hand not showing on the previews, the link is clickable, but it's not visible
Some markdown example:
- Google
	- https://www.google.com
	- [google url](https://google.com)
```
- Google
	- https://www.google.com
	- [google url](https://google.com)
```

**Comment by ajilderda** [comment]
Yes good one, this is solved with the latest release.
