### ISSUE TITLE
does not display properly chemical formulas with \ce{} tags

### ISSUE THREAD

**Issue by SouthPoleCat** [ajilderda/joplin-macos-native-theme#15]
Beautiful theme, but unfortunately does not play well with \ce{} tags.

**Comment by ajilderda** [comment]
Joplin has so many Markdown features I didn't know about!

For my own reference:
https://joplinapp.org/markdown/

**Comment by ajilderda** [comment]
@SouthPoleCat This should be fixed in the latest release can you please check?

**Comment by SouthPoleCat** [comment]
Yes, it is fixed now. Beautiful theme, thank you!
