### ISSUE TITLE
Theme doesn't take into account max-width introduced in latest joplin version

### ISSUE THREAD

**Issue by DanielNetoP** [ajilderda/joplin-macos-native-theme#16]
I'm talking about this commit here https://github.com/laurent22/joplin/commit/8063c94ff7133948604e7dc6bf0c13f8402e11ff
on the [2.3.5 version](https://github.com/laurent22/joplin/releases/tag/v2.3.5) where the user can select the max width of the preview side, defaults to 600 but users might want the old style back which is 0, and also can play with the values to get one that fits their needs.

**Comment by ajilderda** [comment]
Good one, I've removed the setting in the latest release.

**Comment by DanielNetoP** [comment]
In the `1.2.0` release the values we set in the appearance settings is respected, however isn't the padding of `2.8rem` too big?
<img width="868" alt="image" src="https://user-images.githubusercontent.com/10155766/130114605-111647be-1b58-4a2e-aba8-107ecc8a9daa.png">


I was thinking that this was a change because of the 2.3.5 update but apparently it was already like this on 2.3.3 but I didn't noticed it.

**Comment by ajilderda** [comment]
When having the editors side-by-side, yes it's maybe a bit too much. But I can't target that view state specifically. You can easily override the padding in the userchrome.css though.

**Comment by DanielNetoP** [comment]
Yeah, that's what I was doing 😄  just wanted to leave a note, I didn't noticed this before, that's why was wondering if it could've been the plugin, but I've already looked into the code and it's there from the start, so I really must not have been paying attention 🤦
