### ISSUE TITLE
Unreadable links in the Markdown editor

### ISSUE THREAD

**Issue by broslavski** [ajilderda/joplin-macos-native-theme#17]
Please change the link styles, as their display is very hard to read in the Markdown editor:

[Example](https://share.getcloudapp.com/8Lu57jKy).

You can take URL styles from the Apple notes to make them close to Mac OS UI standards:

[Example](https://share.getcloudapp.com/Wnu0bGPZ).

There is also one overlay bug on the add link window:

[Example](https://share.getcloudapp.com/eDuR16XX).

**Comment by ajilderda** [comment]
Hi @broslavski, you can change the appearance of the Markdown editor with the 'Markdown editor light'-setting.

The overlay bug on the add link window should be fixed with the latest release.
