### ISSUE TITLE
Exporting PDF

### ISSUE THREAD

**Issue by Xindi7** [ajilderda/joplin-macos-native-theme#24]
## **Issue**
When exporting an individual note to the pdf, css looking code is also exported in the document. For example a one and a half page document is exported with the theming as well and becomes 11 pages.
## **Ways to replicate**
Export a note when the theme is turned on. If you disable the plugin and export again you can see that it exports normally.
Thanks for this great plugin

**Comment by ajilderda** [comment]
@Xindi7 This should be fixed in version 1.2.5. Do let me know if that is not the case. Thanks for reporting!
