### ISSUE TITLE
Icon not displayed

### ISSUE THREAD

**Issue by GengchenXU** [ajilderda/joplin-macos-native-theme#27]
![image](https://user-images.githubusercontent.com/56543168/132154512-482162ff-1d6c-4a1f-99de-5bfd1d9524de.png)
![image](https://user-images.githubusercontent.com/56543168/132154518-dd4b7c83-5175-45f4-93d0-bf6c9bde301e.png)
My options
![image](https://user-images.githubusercontent.com/56543168/132154655-690a09f4-89a7-47ea-9613-6ef427856d14.png)

**Comment by ajilderda** [comment]
Hi @GengchenXU , is this on Windows or Linux? 

Does installing the webfont solve your issue?
https://github.com/ajilderda/joplin-macos-native-theme/raw/main/src/webfont/phosphor.ttf

**Comment by GengchenXU** [comment]
> Hi @GengchenXU , is this on Windows or Linux?
> 
> Does installing the webfont solve your issue?
> https://github.com/ajilderda/joplin-macos-native-theme/raw/main/src/webfont/phosphor.ttf
on windows

**Comment by GengchenXU** [comment]
> Hi @GengchenXU , is this on Windows or Linux?
> 
> Does installing the webfont solve your issue?
> https://github.com/ajilderda/joplin-macos-native-theme/raw/main/src/webfont/phosphor.ttf

Thank you, I just saw the https://github.com/ajilderda/joplin-macos-native-theme/issues/21
