### ISSUE TITLE
In markdown editor, bolded text is unreadable light gray color

### ISSUE THREAD

**Issue by joshanderson1971** [ajilderda/joplin-macos-native-theme#29]
I just started using this plugin theme and so far I love it, however I'm noticing some readability issues with the markdown editor.

![image](https://user-images.githubusercontent.com/85001299/133148850-aa5c8c26-3a89-4a24-9f18-ac6a4256f8a2.png)

You can see in the screenshot the 4 items in the `**bold**` style are very light gray and almost unreadable. 

I'm not noticing this with any other styling so far.

Thanks
Josh

**Comment by ajilderda** [comment]
Hi @joshanderson1971 , I think this was fixed with recent changes in Joplin's editor. This is what I see:
<img width="278" alt="image" src="https://user-images.githubusercontent.com/487182/141691414-85f3ecef-8620-4473-a3da-d9e4ad8702b1.png">

Feel free to reopen if the issue still occurs for you.
