### ISSUE TITLE
Checkboxes do not show 

### ISSUE THREAD

**Issue by Xindi7** [ajilderda/joplin-macos-native-theme#30]
Checkboxes do not show if I try to use them after adding text to the note.  
OS: Win 10
Joplin version: Latest

**Comment by Xindi7** [comment]
Hi. This is how it looks. In the place of the usual box there is nothing. However, it can still be completed by clicking the empty space where the box would normally show up but I can not uncheck the box either.
![image](https://user-images.githubusercontent.com/89727118/137603873-fcf513a2-6490-416e-9590-4aba0f50392b.png)

**Comment by ajilderda** [comment]
Does it work when you disable all other plugins?

**Comment by ajilderda** [comment]
@Xindi7  Weird, there is no way for me to recreate your issue. If you provide some more information I can dig into this some more, else I'll close this issue eventually.
