### ISSUE TITLE
Feature Request: Solarized Dark

### ISSUE THREAD

**Issue by jkodroff** [ajilderda/joplin-macos-native-theme#31]
Would it be possible to add Solarized Dark as a dark theme in the options?

**Comment by ajilderda** [comment]
I don't plan to do so, but you can give it a go by overwriting the custom properties. Let me know if you need help with that.

**Comment by jkodroff** [comment]
If you have a PR that adds a single theme that I could reference, I should be able to throw together a PR to add the theme.
