### ISSUE TITLE
Lack of readability in the search bar with the dark theme and some accents

### ISSUE THREAD

**Issue by Klemet** [ajilderda/joplin-macos-native-theme#32]
Hello there !

First of all, thanks a million for your plugin. It looks absolutely wonderful, and makes Joplin even more of a joy to use !

That being said, I noticed a small problem of visibility in the dark theme, when some accent colours are used. Here is an example :

![image](https://user-images.githubusercontent.com/41070328/134784494-caf04a4c-2523-4989-b609-5702ce911c39.png)

As you can see, the keywords of the search are in light grey - which becomes almost invisible with the green accent colour.

I think that this could be fixed by using a darker colour for highlighted elements (research keywords) that are currently selected (with the accent colour as a background). For example, with colour `#646B65` :

![image](https://user-images.githubusercontent.com/41070328/134784576-ac8ab7d4-481b-4d73-98ca-78c954d1dab4.png)

Thanks again for your work, hoping that this will help !

**Comment by ajilderda** [comment]
Thanks for reporting @Klemet ! I've just pushed a fix that should be available in an hour. Let me know if it's working for you.

**Comment by Klemet** [comment]
Thank you, it is much more visible like this : ) !

![image](https://user-images.githubusercontent.com/41070328/135093237-b05d735f-74dd-4910-9373-3d8fe89c4f21.png)

Thank you such a quick fix, and have a nice day !

**Comment by ajilderda** [comment]
🎉 Awesome! Likewise @Klemet! 😊
