### ISSUE TITLE
Markdown Text CSS style override my `userstyle.css`

### ISSUE THREAD

**Issue by ylc395** [ajilderda/joplin-macos-native-theme#34]
This theme's CSS style overrides `userstyle.css` here:

<img width="311" alt="图片" src="https://user-images.githubusercontent.com/12264626/136684203-b5140952-717b-4a00-ba76-77a5e8272269.png">

Is it a intented feature or bug?

**Comment by ajilderda** [comment]
@ylc395 There are styles injected in the markdown editor also, so that might be the case. However, you can probably make the userstyle take precedence by increasing the specificity of your CSS selector.
