### ISSUE TITLE
Markdown table not readable in viewer in dark mode

### ISSUE THREAD

**Issue by manthanf1** [ajilderda/joplin-macos-native-theme#36]
When using dark mode in the latest version of this extension, the markdown table is rendered like so:

![Screenshot](https://user-images.githubusercontent.com/65068524/137981389-1ae06e98-95c4-4d88-bce2-f9214ffd5455.png)

As you can see, this is not very readable (grey text on black background).

In light mode, the table is rendered as so
![Screenshot from 2021-10-20 01-23-16](https://user-images.githubusercontent.com/65068524/137981544-fc179242-4256-44fb-b87d-dbc4aa2aa43f.png)

Here, alternate rows in table have lighter shades (with black text)

**Proposed solutions:**
1) Change the color palette of table in dark mode from alternating black and white to two shades of dark.
2) Change the text color in dark mode in tables to white from grey
The rest of the dark theme has white text color

**Comment by ajilderda** [comment]
Thanks @manthanf1 , I've just released a new version that should fix this issue and will be available within the next hour.

**Comment by manthanf1** [comment]
Hi @andrejilderda sorry to reopen the issue, this is the only way I could get in touch with you.

I've recently been doxxed by my username, and so will be changing my username soon. Issue is older comments referencing me by my old username won't automatically update to my new username. 

Could you please update [this](https://github.com/andrejilderda/joplin-macos-native-theme/issues/36#issuecomment-968332988) comment to remove the username and delete that edit history, or delete your comment referencing me entirely? 

Many thanks for your help. Apologies for the weird request.
