### ISSUE TITLE
Sidebar "new notebook" button does not align with text on the left

### ISSUE THREAD

**Issue by lifehome** [ajilderda/joplin-macos-native-theme#37]
The button will be jiggling whenever the user hovers the nearby area, causing an inconsistent UX. Also, the button is not really align to the right...

I do try to find out the cause, but it seems the text on the left are 31px, and the button is 32px, plus the padding and margins in that area are not really the same... Just can't figure out why is it doing like that...

---

### Screencast

https://user-images.githubusercontent.com/1886237/140463972-b7a95243-d14c-4f0f-8f9f-54a9107009da.mov

**Comment by ajilderda** [comment]
Hi @lifehome this should be fixed in the latest version. 🤞
