### ISSUE TITLE
Foldernames no longer visible on Joplin-Desktop 2.6.2

### ISSUE THREAD

**Issue by monnypython** [ajilderda/joplin-macos-native-theme#40]
Hi, I've been using your theme for a while. Thanks for that :)
But after the update to 2.6.2 the folder names are no longer displayed.
After deactivating the theme plugin, everything is OK.

![image](https://user-images.githubusercontent.com/42573701/142576598-2aa0d51f-c41f-477e-a1cd-2d5562e7dc80.png)

**Comment by kingfisher77** [comment]
Same here

**Comment by ajilderda** [comment]
@monnypython @kingfisher77 A fix was just published to npm and should be available in 30 min.. Thanks for noticing! 👯‍♂️

**Comment by kingfisher77** [comment]
> @monnypython @kingfisher77 A fix was just published to npm and should be available in 30 min.. Thanks for noticing! 👯‍♂️

Cool, thank you!
