### ISSUE TITLE
Text Cut Off

### ISSUE THREAD

**Issue by ScriptInfra** [ajilderda/joplin-macos-native-theme#41]
It appears the text of the notebook is getting cut off as shown below:

![image](https://user-images.githubusercontent.com/63025323/142901492-8413641b-4d91-4c61-8293-ff5d1264500f.png)

Below is a screenshot without the plugin applied:

![image](https://user-images.githubusercontent.com/63025323/142901618-7a43ad46-329e-46f3-b763-af6a841acd1f.png)

I am using the latest version of Joplin:

Joplin 2.5.12 (prod, win32)

Client ID: 9921efa6123249f1ab720d6282883310
Sync Version: 3
Profile Version: 39
Keychain Supported: Yes

Revision: 884b86f

P.S. Huge thanks for creating this plugin, it makes Joplin look much more modern.

**Comment by ajilderda** [comment]
Thanks @ScriptInfra , just published a fix that should be available within 30 min.. Happy to hear you enjoy the theme!

**Comment by ScriptInfra** [comment]
Really appreciate the quick update on this, @ajilderda! I have updated both Linux and Windows plug-ins and they both appear to  be functioning as expected. 

Unrelated to this issue, I was curious if it was possible to also update the Options UI with this theme (Tools > Options)?

Additionally, I was also curious if the UI prompts could have the theme applied? E.g. check for updates, About Joplin.

![image](https://user-images.githubusercontent.com/63025323/142956845-6a0e13d8-ccda-458f-ad41-0b03e61a4ccf.png)

![image](https://user-images.githubusercontent.com/63025323/142956869-a107d496-c010-4035-a3f5-325601b5078d.png)
