### ISSUE TITLE
Syncstatus is hard to read

### ISSUE THREAD

**Issue by monnypython** [ajilderda/joplin-macos-native-theme#43]
Hi,
when Apearance is set to "Light with dark Sidebar" the Syncstatus is hard to read:

Light (good): ![joplin_macosTheme_light](https://user-images.githubusercontent.com/42573701/143857485-81b6da8f-95ec-4768-baf9-d975b86f36f2.png)|
Dark (good): ![joplin_macosTheme_dark](https://user-images.githubusercontent.com/42573701/143857722-351464d9-f57c-4f45-8bb3-6c7d6d875bc3.png) |
Dark Sidebar (bad):![joplin_macosTheme_darkSidebar](https://user-images.githubusercontent.com/42573701/143857797-3befbb91-1a1f-439c-a192-f0c6e42620ec.png)|

**Comment by ajilderda** [comment]
Hi @monnypython , thanks for reporting. I've just pushed a fix that'll be available anytime. Let me know if it doesn't work!
