### ISSUE TITLE
Styling the Outline plugin

### ISSUE THREAD

**Issue by andrei-a-papou** [ajilderda/joplin-macos-native-theme#5]
Thank you for this great project. Joplin is powerful, but the stock UX/UI is lacking and this theme is very refreshing. Using it on Ubuntu 20.04 with no issues so far.

I use the Outline plugin and with the macOS theme it kinda sticks out like a sore thumb. I've added the following lines to the CSS to make it look better (give it some space, remove the weird bottom border and add a vertical divider on the right):

```
 /* NB: Outline plugin adjustments; assumes the Outline is placed between the note list and the editor. */
 #plugin-view-outline-outline\.panel {
   border-bottom: none;
   border-right: 1px solid var(--g-gridColor);
   padding: 12px 0 0 5px;
 } 
```

**Before:**
![image](https://user-images.githubusercontent.com/30468319/127988974-a3a6fd14-4d6a-4d49-a0df-9968c573fbce.png)

**After:**
![image](https://user-images.githubusercontent.com/30468319/127989108-1b7fc0b7-4f40-4956-a366-523304cb9851.png)

Question: Is it possible to further style things inside the Outline plugin's iframe? Like the header, for example. I love how you made the _Notebooks_ and _Tags_ headers less prominent in the sidebar, which draws attention to the content.

**Comment by ajilderda** [comment]
@andrei-a-papou There's not so much I can do about the contents of the Outline panel, since the styles are not injected into panels provided by plugins. I did however changed a few things so that added panels have dividers (so you don't have to use the `border-right`-line anymore). Also the missing outline icon next to the 'Note properties'-icon I've added.

**Comment by andrei-a-papou** [comment]
Yes, I forgot to mention the missing toolbar icon, thanks for catching it! Seems that the latest update of the Outline plugin hid the weird bottom border also. Nice!
