### ISSUE TITLE
unstyled search panel

### ISSUE THREAD

**Issue by andrei-a-papou** [ajilderda/joplin-macos-native-theme#6]
Hello and thank you for this awesome theme. Just noticed that the "search in note" panel (_Edit -> Search in current note_) appears unstyled.

Searching in editor:
![image](https://user-images.githubusercontent.com/30468319/128134206-b9af3aae-7d4f-4050-99c2-6dece09ceac9.png)

Searching in viewer:
![image](https://user-images.githubusercontent.com/30468319/128133827-31d50642-86f3-42f9-8456-451f758bc934.png)

Joplin 2.1.9, Ubuntu 20.04, macOS theme 1.1.1

Can this be fixed? Would be willing to test  on my side!

**Comment by ajilderda** [comment]
Yes, I overlooked this one. It should look nicer now with the latest version of the plugin (1.1.0).

**Comment by andrei-a-papou** [comment]
indeed it does, thanks!
