### ISSUE TITLE
Close button label color for note stats

### ISSUE THREAD

**Issue by andrei-a-papou** [ajilderda/joplin-macos-native-theme#7]
The Close button in the note statistics dialog (_Note -> Statistics..._) is black/dark gray:

![image](https://user-images.githubusercontent.com/30468319/128135177-c46d219b-2c28-4fcd-852b-1a95442f2efc.png)

Whereas, for example, the Tags dialog primary button (OK) uses white color for the label: 
![image](https://user-images.githubusercontent.com/30468319/128134933-6b87f9c7-4710-4387-9143-0134b40460da.png)

This seems inconsistent. Is this the expected look for dialogs with only one button?

**Comment by andrei-a-papou** [comment]
This is on Joplin 2.1.9, Ubuntu 20.04, macOS theme 1.1.1

**Comment by ajilderda** [comment]
Thanks for reporting this. This should be fixed in the latest version.

**Comment by andrei-a-papou** [comment]
looks nice now, thanks!
