### ISSUE TITLE
Insert template dialog

### ISSUE THREAD

**Issue by andrei-a-papou** [ajilderda/joplin-macos-native-theme#8]
The dialog under _File -> Templates -> Insert template_ appears to not be completely styled. The blue outline is off, the dropdown field doesn't look right, and it seems the buttons' colors are slightly off (at least the primary button's background gradient is too dim).

This is what it looks like on my machine:
![image](https://user-images.githubusercontent.com/30468319/128135587-9dae9651-612b-48cb-ad2f-e3597a27d29e.png)

And this is the Tags dialog, for example (seems to look right):
![image](https://user-images.githubusercontent.com/30468319/128134933-6b87f9c7-4710-4387-9143-0134b40460da.png)

This is Joplin 2.1.9, Ubuntu 20.04, macOS theme 1.1.1

**Comment by ajilderda** [comment]
Thanks for reporting this issue! This should be fixed in the latest version. Let me know if that's not the case.

**Comment by andrei-a-papou** [comment]
seems to work great with Joplin 2.3.3 and the Templates plugin v1.1.4, thanks!
